#!/usr/bin/env python3

import os
import sys
import helpers

from analyzer import Analyzer
from termcolor import colored

def main():
    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweet name")
        
    # get user tweets
    screen_name = sys.argv[1]
    tweets = helpers.get_user_timeline(screen_name)
    
    if tweets is None:
        sys.exit("Couldn't get tweets")
    
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    for tweet in tweets[:50]:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            color = "green"
        elif score < 0.0:
            color = "red"
        else:
            color = "yellow"
        print(colored("{0} {1}".format(score, tweet), color))

if __name__ == "__main__":
    main()
